name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  schedule:
    - cron:  '0 8 * * *'

jobs:
  run-tests:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 9
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: [3.5, 3.6, 3.7]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get Python Package Location
        run: |
          echo "::set-output name=path::$(python -c 'import site; print(site.getusersitepackages())')"
        id: get_location

      - name: Activate Cache
        uses: actions/cache@preview
        with:
          path: ${{ steps.get_location.outputs.path }}
          key: pytest-${{ matrix.os }}-${{ matrix.python-version }}-libs-${{ hashFiles('**/**equirement*.txt') }}
          restore-keys: |
            pytest-${{ matrix.os }}-${{ matrix.python-version }}-libs-

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade -r requirements.txt --user --no-warn-script-location
          pip install coveralls

      - name: Test with pytest
        run: |
          coverage run ./patchalerts/scanner.py --test

